# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 125ddb614c82c1cf7f692523e92d29e804d36b2fba0158e703ea30d647b94759a96ce2f4a8174e6a5e71ef8c562b447fd1910573ab40966ad3cc067e32d21bb6

test:
  secret_key_base: 51bef365c3e07355a39159702374fb0c510a5d3c6374965d32b5fc1a9094e9f51e4cbae6dd77b0f8aca04ad8cd015639c9439bc598e2c429e66c073b5bae78d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
